// <auto-generated />
using System;
using MicroClassroom.Customer.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace MicroClassroom.Customer.Migrations
{
    [DbContext(typeof(CustomerHttpApiHostMigrationsDbContext))]
    [Migration("20220727064137_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MicroClassroom.Customer.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasComment("主键标识");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Content")
                        .HasComment("评论内容");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CourseId")
                        .HasComment("课程id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateAt")
                        .HasComment("评论时间");

                    b.Property<int>("Star")
                        .HasColumnType("int")
                        .HasColumnName("Star")
                        .HasComment("评分");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId")
                        .HasComment("租户id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId")
                        .HasComment("用户id");

                    b.HasKey("Id")
                        .HasName("pk_comment_id");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("MicroClassroom.Customer.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasComment("主键标识");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CourseId")
                        .HasComment("课程id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateAt")
                        .HasComment("评论时间");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Discount")
                        .HasComment("优惠金额");

                    b.Property<bool?>("IsPay")
                        .HasColumnType("bit")
                        .HasColumnName("IsPay")
                        .HasComment("实付付款");

                    b.Property<decimal?>("PayIn")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("PayIn")
                        .HasComment("实付金额");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Price")
                        .HasComment("课程价格");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId")
                        .HasComment("租户id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId")
                        .HasComment("用户id");

                    b.HasKey("Id")
                        .HasName("pk_purchase_id");

                    b.ToTable("Purchase", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
